- name: get package facts
  package_facts:
    manager: auto

- name: get haproxy rpm from centos repo
  shell: wget -r -l1 -np -nd http://mirror.centos.org/centos/7/os/x86_64/Packages/ -P /tmp -A 'haproxy*.rpm'
  when: ansible_facts.packages.haproxy is not defined
  warn: no

- name    : get haproxy rpm name in /tmp
  shell   : ls /tmp/haproxy*.rpm
  register: path_files

- debug:
    var: path_files

- name: install haproxy
  yum:
    name: "{{ item }}"
    state: present
  register: haproxy_installed
  until: haproxy_installed is succeeded
  with_items: "{{ path_files.stdout_lines }}"
  when: ansible_facts.packages.haproxy is not defined

- name: remove temp haproxy rpm
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ path_files.stdout_lines }}"

